Class {
	#name : #FamixFortran2003ImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'Famix-Fortran2003-Entities'
}

{ #category : #testing }
FamixFortran2003ImportingContext >> importAccess [
	<generated>
	^ self import: FamixFortran2003Access
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importBody [
	<generated>
	^ self import: FamixFortran2003Body
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importComment [
	<generated>
	^ self import: FamixFortran2003Comment
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importEntity [
	<generated>
	^ self import: FamixFortran2003Entity
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importFile [
	<generated>
	^ self import: FamixFortran2003File
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importFunction [
	<generated>
	^ self import: FamixFortran2003Function
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importInclude [
	<generated>
	^ self import: FamixFortran2003Include
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importInvocation [
	<generated>
	^ self import: FamixFortran2003Invocation
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importModule [
	<generated>
	^ self import: FamixFortran2003Module
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importNamedConstant [
	<generated>
	^ self import: FamixFortran2003NamedConstant
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importNamedEntity [
	<generated>
	^ self import: FamixFortran2003NamedEntity
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importPUComment [
	<generated>
	^ self import: FamixFortran2003PUComment
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importParameter [
	<generated>
	^ self import: FamixFortran2003Parameter
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importProcedure [
	<generated>
	^ self import: FamixFortran2003Procedure
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importProgram [
	<generated>
	^ self import: FamixFortran2003Program
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importProgramUnit [
	<generated>
	^ self import: FamixFortran2003ProgramUnit
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importSourceAnchor [
	<generated>
	^ self import: FamixFortran2003SourceAnchor
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importSourceLanguage [
	<generated>
	^ self import: FamixFortran2003SourceLanguage
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importSourceTextAnchor [
	<generated>
	^ self import: FamixFortran2003SourceTextAnchor
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importSourcedEntity [
	<generated>
	^ self import: FamixFortran2003SourcedEntity
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importSubroutine [
	<generated>
	^ self import: FamixFortran2003Subroutine
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importUnknownSourceLanguage [
	<generated>
	^ self import: FamixFortran2003UnknownSourceLanguage
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importUsage [
	<generated>
	^ self import: FamixFortran2003Usage
]

{ #category : #testing }
FamixFortran2003ImportingContext >> importVariable [
	<generated>
	^ self import: FamixFortran2003Variable
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportAccess [
	<generated>
	^ self shouldImport: FamixFortran2003Access
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportBody [
	<generated>
	^ self shouldImport: FamixFortran2003Body
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportComment [
	<generated>
	^ self shouldImport: FamixFortran2003Comment
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportEntity [
	<generated>
	^ self shouldImport: FamixFortran2003Entity
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportFile [
	<generated>
	^ self shouldImport: FamixFortran2003File
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportFunction [
	<generated>
	^ self shouldImport: FamixFortran2003Function
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportInclude [
	<generated>
	^ self shouldImport: FamixFortran2003Include
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportInvocation [
	<generated>
	^ self shouldImport: FamixFortran2003Invocation
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportModule [
	<generated>
	^ self shouldImport: FamixFortran2003Module
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportNamedConstant [
	<generated>
	^ self shouldImport: FamixFortran2003NamedConstant
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportNamedEntity [
	<generated>
	^ self shouldImport: FamixFortran2003NamedEntity
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportPUComment [
	<generated>
	^ self shouldImport: FamixFortran2003PUComment
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportParameter [
	<generated>
	^ self shouldImport: FamixFortran2003Parameter
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportProcedure [
	<generated>
	^ self shouldImport: FamixFortran2003Procedure
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportProgram [
	<generated>
	^ self shouldImport: FamixFortran2003Program
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportProgramUnit [
	<generated>
	^ self shouldImport: FamixFortran2003ProgramUnit
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportSourceAnchor [
	<generated>
	^ self shouldImport: FamixFortran2003SourceAnchor
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportSourceLanguage [
	<generated>
	^ self shouldImport: FamixFortran2003SourceLanguage
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportSourceTextAnchor [
	<generated>
	^ self shouldImport: FamixFortran2003SourceTextAnchor
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportSourcedEntity [
	<generated>
	^ self shouldImport: FamixFortran2003SourcedEntity
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportSubroutine [
	<generated>
	^ self shouldImport: FamixFortran2003Subroutine
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportUnknownSourceLanguage [
	<generated>
	^ self shouldImport: FamixFortran2003UnknownSourceLanguage
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportUsage [
	<generated>
	^ self shouldImport: FamixFortran2003Usage
]

{ #category : #testing }
FamixFortran2003ImportingContext >> shouldImportVariable [
	<generated>
	^ self shouldImport: FamixFortran2003Variable
]
