"
pucomment comment
"
Class {
	#name : #FamixFortran2003PUComment,
	#superclass : #FamixFortran2003Entity,
	#traits : 'FamixFortran2003TProgramUnit',
	#classTraits : 'FamixFortran2003TProgramUnit classTrait',
	#category : #'Famix-Fortran2003-Entities-Entities'
}

{ #category : #meta }
FamixFortran2003PUComment class >> annotation [

	<FMClass: #PUComment super: #FamixFortran2003Entity>
	<package: #'Famix-Fortran2003-Entities'>
	<generated>
	^self
]
