Class {
	#name : #FamixFortran2003SourcedEntity,
	#superclass : #FamixFortran2003Entity,
	#traits : 'FamixTSourceEntity',
	#classTraits : 'FamixTSourceEntity classTrait',
	#category : #'Famix-Fortran2003-Entities-Entities'
}

{ #category : #meta }
FamixFortran2003SourcedEntity class >> annotation [

	<FMClass: #SourcedEntity super: #FamixFortran2003Entity>
	<package: #'Famix-Fortran2003-Entities'>
	<generated>
	^self
]
