Class {
	#name : #FamixFortran2003NamedEntity,
	#superclass : #FamixFortran2003Entity,
	#traits : 'FamixTNamedEntity',
	#classTraits : 'FamixTNamedEntity classTrait',
	#category : #'Famix-Fortran2003-Entities-Entities'
}

{ #category : #meta }
FamixFortran2003NamedEntity class >> annotation [

	<FMClass: #NamedEntity super: #FamixFortran2003Entity>
	<package: #'Famix-Fortran2003-Entities'>
	<generated>
	^self
]
