Class {
	#name : #FamixFortran2003SourceTextAnchor,
	#superclass : #FamixFortran2003SourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-Fortran2003-Entities-Entities'
}

{ #category : #meta }
FamixFortran2003SourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixFortran2003SourceAnchor>
	<package: #'Famix-Fortran2003-Entities'>
	<generated>
	^self
]
