Class {
	#name : #FamixFortran2003SourceLanguage,
	#superclass : #FamixFortran2003Entity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Famix-Fortran2003-Entities-Entities'
}

{ #category : #meta }
FamixFortran2003SourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #FamixFortran2003Entity>
	<package: #'Famix-Fortran2003-Entities'>
	<generated>
	^self
]
