Class {
	#name : #FamixFortran2003Comment,
	#superclass : #FamixFortran2003SourcedEntity,
	#traits : 'FamixTComment',
	#classTraits : 'FamixTComment classTrait',
	#category : #'Famix-Fortran2003-Entities-Entities'
}

{ #category : #meta }
FamixFortran2003Comment class >> annotation [

	<FMClass: #Comment super: #FamixFortran2003SourcedEntity>
	<package: #'Famix-Fortran2003-Entities'>
	<generated>
	^self
]
