Class {
	#name : #FamixFortran2003SourceAnchor,
	#superclass : #FamixFortran2003Entity,
	#traits : 'FamixTSourceAnchor',
	#classTraits : 'FamixTSourceAnchor classTrait',
	#category : #'Famix-Fortran2003-Entities-Entities'
}

{ #category : #meta }
FamixFortran2003SourceAnchor class >> annotation [

	<FMClass: #SourceAnchor super: #FamixFortran2003Entity>
	<package: #'Famix-Fortran2003-Entities'>
	<generated>
	^self
]
