Class {
	#name : #FamixFortran2003UnknownSourceLanguage,
	#superclass : #FamixFortran2003SourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-Fortran2003-Entities-Entities'
}

{ #category : #meta }
FamixFortran2003UnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixFortran2003SourceLanguage>
	<package: #'Famix-Fortran2003-Entities'>
	<generated>
	^self
]
