Class {
	#name : #FamixFortran2003Model,
	#superclass : #MooseModel,
	#category : #'Famix-Fortran2003-Entities-Model'
}

{ #category : #accessing }
FamixFortran2003Model class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
FamixFortran2003Model class >> annotation [
	<FMClass: #FamixFortran2003Model super: #MooseModel>
	<package: #'Famix-Fortran2003-Entities'>
	<generated>
]
