"
invocation comment
"
Class {
	#name : #FamixFortran2003Invocation,
	#superclass : #FamixFortran2003Entity,
	#traits : 'FamixFortran2003TStaticInvocation + FamixTAssociation',
	#classTraits : 'FamixFortran2003TStaticInvocation classTrait + FamixTAssociation classTrait',
	#category : #'Famix-Fortran2003-Entities-Entities'
}

{ #category : #meta }
FamixFortran2003Invocation class >> annotation [

	<FMClass: #Invocation super: #FamixFortran2003Entity>
	<package: #'Famix-Fortran2003-Entities'>
	<generated>
	^self
]
