"
Function
"
Class {
	#name : #FamixFortranFunction,
	#superclass : #FamixFortranExternalProcedure,
	#traits : 'FamixTTypedEntity',
	#classTraits : 'FamixTTypedEntity classTrait',
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranFunction class >> annotation [

	<FMClass: #Function super: #FamixFortranExternalProcedure>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]
