Class {
	#name : #FamixFortranImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'Famix-Fortran-Entities'
}

{ #category : #testing }
FamixFortranImportingContext >> importBlockData [
	<generated>
	^ self import: FamixFortranBlockData
]

{ #category : #testing }
FamixFortranImportingContext >> importComment [
	<generated>
	^ self import: FamixFortranComment
]

{ #category : #testing }
FamixFortranImportingContext >> importEntity [
	<generated>
	^ self import: FamixFortranEntity
]

{ #category : #testing }
FamixFortranImportingContext >> importExternalProcedure [
	<generated>
	^ self import: FamixFortranExternalProcedure
]

{ #category : #testing }
FamixFortranImportingContext >> importFunction [
	<generated>
	^ self import: FamixFortranFunction
]

{ #category : #testing }
FamixFortranImportingContext >> importInvocation [
	<generated>
	^ self import: FamixFortranInvocation
]

{ #category : #testing }
FamixFortranImportingContext >> importModule [
	<generated>
	^ self import: FamixFortranModule
]

{ #category : #testing }
FamixFortranImportingContext >> importParameter [
	<generated>
	^ self import: FamixFortranParameter
]

{ #category : #testing }
FamixFortranImportingContext >> importProgram [
	<generated>
	^ self import: FamixFortranProgram
]

{ #category : #testing }
FamixFortranImportingContext >> importProgramFile [
	<generated>
	^ self import: FamixFortranProgramFile
]

{ #category : #testing }
FamixFortranImportingContext >> importSubroutine [
	<generated>
	^ self import: FamixFortranSubroutine
]

{ #category : #testing }
FamixFortranImportingContext >> importVariable [
	<generated>
	^ self import: FamixFortranVariable
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportBlockData [
	<generated>
	^ self shouldImport: FamixFortranBlockData
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportComment [
	<generated>
	^ self shouldImport: FamixFortranComment
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportEntity [
	<generated>
	^ self shouldImport: FamixFortranEntity
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportExternalProcedure [
	<generated>
	^ self shouldImport: FamixFortranExternalProcedure
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportFunction [
	<generated>
	^ self shouldImport: FamixFortranFunction
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportInvocation [
	<generated>
	^ self shouldImport: FamixFortranInvocation
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportModule [
	<generated>
	^ self shouldImport: FamixFortranModule
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportParameter [
	<generated>
	^ self shouldImport: FamixFortranParameter
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportProgram [
	<generated>
	^ self shouldImport: FamixFortranProgram
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportProgramFile [
	<generated>
	^ self shouldImport: FamixFortranProgramFile
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportSubroutine [
	<generated>
	^ self shouldImport: FamixFortranSubroutine
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportVariable [
	<generated>
	^ self shouldImport: FamixFortranVariable
]
