"
UnresolvedBehavioral
"
Class {
	#name : #FamixFortranUnresolvedBehavioral,
	#superclass : #FamixFortranExternalProcedure,
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranUnresolvedBehavioral class >> annotation [

	<FMClass: #UnresolvedBehavioral super: #FamixFortranExternalProcedure>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]

{ #category : #testing }
FamixFortranUnresolvedBehavioral >> isUnresolvedBehavioral [

	<generated>
	^ true
]
