"
SrcSpan
"
Class {
	#name : #FamixFortranIndexedFileAnchor,
	#superclass : #FamixFortranSourceAnchor,
	#traits : 'FamixTFileNavigation',
	#classTraits : 'FamixTFileNavigation classTrait',
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranIndexedFileAnchor class >> annotation [

	<FMClass: #IndexedFileAnchor super: #FamixFortranSourceAnchor>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]
