Class {
	#name : #FamixFortranImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'Famix-Fortran-Entities'
}

{ #category : #testing }
FamixFortranImportingContext >> importAttrAllocatable [
	<generated>
	^ self import: FamixFortranAttrAllocatable
]

{ #category : #testing }
FamixFortranImportingContext >> importAttrDimension [
	<generated>
	^ self import: FamixFortranAttrDimension
]

{ #category : #testing }
FamixFortranImportingContext >> importAttrIntent [
	<generated>
	^ self import: FamixFortranAttrIntent
]

{ #category : #testing }
FamixFortranImportingContext >> importAttrPointer [
	<generated>
	^ self import: FamixFortranAttrPointer
]

{ #category : #testing }
FamixFortranImportingContext >> importAttrSuffix [
	<generated>
	^ self import: FamixFortranAttrSuffix
]

{ #category : #testing }
FamixFortranImportingContext >> importAttrTarget [
	<generated>
	^ self import: FamixFortranAttrTarget
]

{ #category : #testing }
FamixFortranImportingContext >> importAttrValue [
	<generated>
	^ self import: FamixFortranAttrValue
]

{ #category : #testing }
FamixFortranImportingContext >> importComment [
	<generated>
	^ self import: FamixFortranComment
]

{ #category : #testing }
FamixFortranImportingContext >> importDoSpecification [
	<generated>
	^ self import: FamixFortranDoSpecification
]

{ #category : #testing }
FamixFortranImportingContext >> importEntity [
	<generated>
	^ self import: FamixFortranEntity
]

{ #category : #testing }
FamixFortranImportingContext >> importPUBlockData [
	<generated>
	^ self import: FamixFortranPUBlockData
]

{ #category : #testing }
FamixFortranImportingContext >> importPUComment [
	<generated>
	^ self import: FamixFortranPUComment
]

{ #category : #testing }
FamixFortranImportingContext >> importPUFunction [
	<generated>
	^ self import: FamixFortranPUFunction
]

{ #category : #testing }
FamixFortranImportingContext >> importPUMain [
	<generated>
	^ self import: FamixFortranPUMain
]

{ #category : #testing }
FamixFortranImportingContext >> importPUModule [
	<generated>
	^ self import: FamixFortranPUModule
]

{ #category : #testing }
FamixFortranImportingContext >> importProgramFile [
	<generated>
	^ self import: FamixFortranProgramFile
]

{ #category : #testing }
FamixFortranImportingContext >> importSubroutine [
	<generated>
	^ self import: FamixFortranSubroutine
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportAttrAllocatable [
	<generated>
	^ self shouldImport: FamixFortranAttrAllocatable
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportAttrDimension [
	<generated>
	^ self shouldImport: FamixFortranAttrDimension
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportAttrIntent [
	<generated>
	^ self shouldImport: FamixFortranAttrIntent
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportAttrPointer [
	<generated>
	^ self shouldImport: FamixFortranAttrPointer
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportAttrSuffix [
	<generated>
	^ self shouldImport: FamixFortranAttrSuffix
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportAttrTarget [
	<generated>
	^ self shouldImport: FamixFortranAttrTarget
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportAttrValue [
	<generated>
	^ self shouldImport: FamixFortranAttrValue
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportComment [
	<generated>
	^ self shouldImport: FamixFortranComment
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportDoSpecification [
	<generated>
	^ self shouldImport: FamixFortranDoSpecification
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportEntity [
	<generated>
	^ self shouldImport: FamixFortranEntity
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportPUBlockData [
	<generated>
	^ self shouldImport: FamixFortranPUBlockData
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportPUComment [
	<generated>
	^ self shouldImport: FamixFortranPUComment
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportPUFunction [
	<generated>
	^ self shouldImport: FamixFortranPUFunction
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportPUMain [
	<generated>
	^ self shouldImport: FamixFortranPUMain
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportPUModule [
	<generated>
	^ self shouldImport: FamixFortranPUModule
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportProgramFile [
	<generated>
	^ self shouldImport: FamixFortranProgramFile
]

{ #category : #testing }
FamixFortranImportingContext >> shouldImportSubroutine [
	<generated>
	^ self shouldImport: FamixFortranSubroutine
]
