"
BlockData
"
Class {
	#name : #FamixFortranBlockData,
	#superclass : #FamixFortranEntity,
	#traits : 'FamixFortranTProgramUnit',
	#classTraits : 'FamixFortranTProgramUnit classTrait',
	#category : #'Famix-Fortran-Entities-Entities'
}

{ #category : #meta }
FamixFortranBlockData class >> annotation [

	<FMClass: #BlockData super: #FamixFortranEntity>
	<package: #'Famix-Fortran-Entities'>
	<generated>
	^self
]
