"
a formal parameter
"
Class {
	#name : #FamixFortran77Parameter,
	#superclass : #FamixFortran77Entity,
	#traits : 'FamixTParameter',
	#classTraits : 'FamixTParameter classTrait',
	#category : #'Famix-Fortran77-Entities-Entities'
}

{ #category : #meta }
FamixFortran77Parameter class >> annotation [

	<FMClass: #Parameter super: #FamixFortran77Entity>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
