"
a comment belongs to fortran file
"
Class {
	#name : #FamixFortran77PUComment,
	#superclass : #FamixFortran77ProgramUnit,
	#traits : 'FamixTComment',
	#classTraits : 'FamixTComment classTrait',
	#category : #'Famix-Fortran77-Entities-Entities'
}

{ #category : #meta }
FamixFortran77PUComment class >> annotation [

	<FMClass: #PUComment super: #FamixFortran77ProgramUnit>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
