Class {
	#name : #FamixFortran77Model,
	#superclass : #MooseModel,
	#category : #'Famix-Fortran77-Entities-Model'
}

{ #category : #accessing }
FamixFortran77Model class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
FamixFortran77Model class >> annotation [
	<FMClass: #FamixFortran77Model super: #MooseModel>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
]
