Class {
	#name : #FamixFortran77ImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'Famix-Fortran77-Entities'
}

{ #category : #testing }
FamixFortran77ImportingContext >> importAccess [
	<generated>
	^ self import: FamixFortran77Access
]

{ #category : #testing }
FamixFortran77ImportingContext >> importComment [
	<generated>
	^ self import: FamixFortran77Comment
]

{ #category : #testing }
FamixFortran77ImportingContext >> importEntity [
	<generated>
	^ self import: FamixFortran77Entity
]

{ #category : #testing }
FamixFortran77ImportingContext >> importFType [
	<generated>
	^ self import: FamixFortran77FType
]

{ #category : #testing }
FamixFortran77ImportingContext >> importIndexedFileAnchor [
	<generated>
	^ self import: FamixFortran77IndexedFileAnchor
]

{ #category : #testing }
FamixFortran77ImportingContext >> importInvocation [
	<generated>
	^ self import: FamixFortran77Invocation
]

{ #category : #testing }
FamixFortran77ImportingContext >> importNamedEntity [
	<generated>
	^ self import: FamixFortran77NamedEntity
]

{ #category : #testing }
FamixFortran77ImportingContext >> importPUBlockdata [
	<generated>
	^ self import: FamixFortran77PUBlockdata
]

{ #category : #testing }
FamixFortran77ImportingContext >> importPUComment [
	<generated>
	^ self import: FamixFortran77PUComment
]

{ #category : #testing }
FamixFortran77ImportingContext >> importPUFunction [
	<generated>
	^ self import: FamixFortran77PUFunction
]

{ #category : #testing }
FamixFortran77ImportingContext >> importPUMain [
	<generated>
	^ self import: FamixFortran77PUMain
]

{ #category : #testing }
FamixFortran77ImportingContext >> importPUProcedure [
	<generated>
	^ self import: FamixFortran77PUProcedure
]

{ #category : #testing }
FamixFortran77ImportingContext >> importPUSubroutine [
	<generated>
	^ self import: FamixFortran77PUSubroutine
]

{ #category : #testing }
FamixFortran77ImportingContext >> importParameter [
	<generated>
	^ self import: FamixFortran77Parameter
]

{ #category : #testing }
FamixFortran77ImportingContext >> importProgramFile [
	<generated>
	^ self import: FamixFortran77ProgramFile
]

{ #category : #testing }
FamixFortran77ImportingContext >> importProgramUnit [
	<generated>
	^ self import: FamixFortran77ProgramUnit
]

{ #category : #testing }
FamixFortran77ImportingContext >> importSourceAnchor [
	<generated>
	^ self import: FamixFortran77SourceAnchor
]

{ #category : #testing }
FamixFortran77ImportingContext >> importSourceLanguage [
	<generated>
	^ self import: FamixFortran77SourceLanguage
]

{ #category : #testing }
FamixFortran77ImportingContext >> importSourceTextAnchor [
	<generated>
	^ self import: FamixFortran77SourceTextAnchor
]

{ #category : #testing }
FamixFortran77ImportingContext >> importSourcedEntity [
	<generated>
	^ self import: FamixFortran77SourcedEntity
]

{ #category : #testing }
FamixFortran77ImportingContext >> importUnknownSourceLanguage [
	<generated>
	^ self import: FamixFortran77UnknownSourceLanguage
]

{ #category : #testing }
FamixFortran77ImportingContext >> importVariable [
	<generated>
	^ self import: FamixFortran77Variable
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportAccess [
	<generated>
	^ self shouldImport: FamixFortran77Access
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportComment [
	<generated>
	^ self shouldImport: FamixFortran77Comment
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportEntity [
	<generated>
	^ self shouldImport: FamixFortran77Entity
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportFType [
	<generated>
	^ self shouldImport: FamixFortran77FType
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportIndexedFileAnchor [
	<generated>
	^ self shouldImport: FamixFortran77IndexedFileAnchor
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportInvocation [
	<generated>
	^ self shouldImport: FamixFortran77Invocation
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportNamedEntity [
	<generated>
	^ self shouldImport: FamixFortran77NamedEntity
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportPUBlockdata [
	<generated>
	^ self shouldImport: FamixFortran77PUBlockdata
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportPUComment [
	<generated>
	^ self shouldImport: FamixFortran77PUComment
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportPUFunction [
	<generated>
	^ self shouldImport: FamixFortran77PUFunction
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportPUMain [
	<generated>
	^ self shouldImport: FamixFortran77PUMain
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportPUProcedure [
	<generated>
	^ self shouldImport: FamixFortran77PUProcedure
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportPUSubroutine [
	<generated>
	^ self shouldImport: FamixFortran77PUSubroutine
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportParameter [
	<generated>
	^ self shouldImport: FamixFortran77Parameter
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportProgramFile [
	<generated>
	^ self shouldImport: FamixFortran77ProgramFile
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportProgramUnit [
	<generated>
	^ self shouldImport: FamixFortran77ProgramUnit
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportSourceAnchor [
	<generated>
	^ self shouldImport: FamixFortran77SourceAnchor
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportSourceLanguage [
	<generated>
	^ self shouldImport: FamixFortran77SourceLanguage
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportSourceTextAnchor [
	<generated>
	^ self shouldImport: FamixFortran77SourceTextAnchor
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportSourcedEntity [
	<generated>
	^ self shouldImport: FamixFortran77SourcedEntity
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportUnknownSourceLanguage [
	<generated>
	^ self shouldImport: FamixFortran77UnknownSourceLanguage
]

{ #category : #testing }
FamixFortran77ImportingContext >> shouldImportVariable [
	<generated>
	^ self shouldImport: FamixFortran77Variable
]
