Class {
	#name : #FamixF77ImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'Famix-Fortran77-Entities'
}

{ #category : #testing }
FamixF77ImportingContext >> importAccess [
	<generated>
	^ self import: FamixF77Access
]

{ #category : #testing }
FamixF77ImportingContext >> importBody [
	<generated>
	^ self import: FamixF77Body
]

{ #category : #testing }
FamixF77ImportingContext >> importComment [
	<generated>
	^ self import: FamixF77Comment
]

{ #category : #testing }
FamixF77ImportingContext >> importEntity [
	<generated>
	^ self import: FamixF77Entity
]

{ #category : #testing }
FamixF77ImportingContext >> importFile [
	<generated>
	^ self import: FamixF77File
]

{ #category : #testing }
FamixF77ImportingContext >> importInclude [
	<generated>
	^ self import: FamixF77Include
]

{ #category : #testing }
FamixF77ImportingContext >> importInvocation [
	<generated>
	^ self import: FamixF77Invocation
]

{ #category : #testing }
FamixF77ImportingContext >> importNamedEntity [
	<generated>
	^ self import: FamixF77NamedEntity
]

{ #category : #testing }
FamixF77ImportingContext >> importPUBlockdata [
	<generated>
	^ self import: FamixF77PUBlockdata
]

{ #category : #testing }
FamixF77ImportingContext >> importPUComment [
	<generated>
	^ self import: FamixF77PUComment
]

{ #category : #testing }
FamixF77ImportingContext >> importPUFunction [
	<generated>
	^ self import: FamixF77PUFunction
]

{ #category : #testing }
FamixF77ImportingContext >> importPUMain [
	<generated>
	^ self import: FamixF77PUMain
]

{ #category : #testing }
FamixF77ImportingContext >> importPUProcedure [
	<generated>
	^ self import: FamixF77PUProcedure
]

{ #category : #testing }
FamixF77ImportingContext >> importPUSubroutine [
	<generated>
	^ self import: FamixF77PUSubroutine
]

{ #category : #testing }
FamixF77ImportingContext >> importParameter [
	<generated>
	^ self import: FamixF77Parameter
]

{ #category : #testing }
FamixF77ImportingContext >> importProgramUnit [
	<generated>
	^ self import: FamixF77ProgramUnit
]

{ #category : #testing }
FamixF77ImportingContext >> importSourceAnchor [
	<generated>
	^ self import: FamixF77SourceAnchor
]

{ #category : #testing }
FamixF77ImportingContext >> importSourceLanguage [
	<generated>
	^ self import: FamixF77SourceLanguage
]

{ #category : #testing }
FamixF77ImportingContext >> importSourceTextAnchor [
	<generated>
	^ self import: FamixF77SourceTextAnchor
]

{ #category : #testing }
FamixF77ImportingContext >> importSourcedEntity [
	<generated>
	^ self import: FamixF77SourcedEntity
]

{ #category : #testing }
FamixF77ImportingContext >> importUnknownSourceLanguage [
	<generated>
	^ self import: FamixF77UnknownSourceLanguage
]

{ #category : #testing }
FamixF77ImportingContext >> importVariable [
	<generated>
	^ self import: FamixF77Variable
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportAccess [
	<generated>
	^ self shouldImport: FamixF77Access
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportBody [
	<generated>
	^ self shouldImport: FamixF77Body
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportComment [
	<generated>
	^ self shouldImport: FamixF77Comment
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportEntity [
	<generated>
	^ self shouldImport: FamixF77Entity
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportFile [
	<generated>
	^ self shouldImport: FamixF77File
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportInclude [
	<generated>
	^ self shouldImport: FamixF77Include
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportInvocation [
	<generated>
	^ self shouldImport: FamixF77Invocation
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportNamedEntity [
	<generated>
	^ self shouldImport: FamixF77NamedEntity
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportPUBlockdata [
	<generated>
	^ self shouldImport: FamixF77PUBlockdata
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportPUComment [
	<generated>
	^ self shouldImport: FamixF77PUComment
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportPUFunction [
	<generated>
	^ self shouldImport: FamixF77PUFunction
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportPUMain [
	<generated>
	^ self shouldImport: FamixF77PUMain
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportPUProcedure [
	<generated>
	^ self shouldImport: FamixF77PUProcedure
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportPUSubroutine [
	<generated>
	^ self shouldImport: FamixF77PUSubroutine
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportParameter [
	<generated>
	^ self shouldImport: FamixF77Parameter
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportProgramUnit [
	<generated>
	^ self shouldImport: FamixF77ProgramUnit
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportSourceAnchor [
	<generated>
	^ self shouldImport: FamixF77SourceAnchor
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportSourceLanguage [
	<generated>
	^ self shouldImport: FamixF77SourceLanguage
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportSourceTextAnchor [
	<generated>
	^ self shouldImport: FamixF77SourceTextAnchor
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportSourcedEntity [
	<generated>
	^ self shouldImport: FamixF77SourcedEntity
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportUnknownSourceLanguage [
	<generated>
	^ self shouldImport: FamixF77UnknownSourceLanguage
]

{ #category : #testing }
FamixF77ImportingContext >> shouldImportVariable [
	<generated>
	^ self shouldImport: FamixF77Variable
]
