Class {
	#name : #FamixFortran77SourceLanguage,
	#superclass : #FamixFortran77Entity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Famix-Fortran77-Entities-Entities'
}

{ #category : #meta }
FamixFortran77SourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #FamixFortran77Entity>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
