Class {
	#name : #FamixFortran77UnknownSourceLanguage,
	#superclass : #FamixFortran77SourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-Fortran77-Entities-Entities'
}

{ #category : #meta }
FamixFortran77UnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixFortran77SourceLanguage>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
