Class {
	#name : #FamixFortran77SourceTextAnchor,
	#superclass : #FamixFortran77SourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-Fortran77-Entities-Entities'
}

{ #category : #meta }
FamixFortran77SourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixFortran77SourceAnchor>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
